[versions]
agp = "8.9.3"
androidLoadingAnimation = "1.0.6"
devicecompat = "1.6"
fastjson = "1.2.83"
fyiban = "1.0.1"
jsoup = "1.21.2"
kotlin = "2.0.0"
kotlinxCoroutinesCore = "1.10.2"
okhttp = "4.12.0"
smartupdatedemo = "1.0.2"
objectbox = "4.3.0"
xxpermissions = "26.5"
core = "1.17.0"
appcompatVersion = "1.7.1"
lifecycleService = "2.10.0"

[libraries]
android-loading-animation = { module = "com.github.OneFeiFan:Android-Loading-Animation", version.ref = "androidLoadingAnimation" }
devicecompat = { module = "com.github.getActivity:DeviceCompat", version.ref = "devicecompat" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }
fyiban = { module = "com.github.OneFeiFan:FYIBAN", version.ref = "fyiban" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
#noinspection Aligned16KB
smartupdatedemo = { module = "com.github.OneFeiFan:SmartUpdateDemo", version.ref = "smartupdatedemo" }
xxpermissions = { module = "com.github.getActivity:XXPermissions", version.ref = "xxpermissions" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library" }
objectbox = { id = "io.objectbox", version.ref = "objectbox" }
