plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.objectbox)
}

android {
    namespace 'com.feifan.fuckingnjit'
    compileSdk 35

    defaultConfig {
//        applicationId "com.feifan.fuckingnjit"
        minSdk 26
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
//    testOptions {
//        unitTests {
//            includeAndroidResources = true
//            all {
//                systemProperty 'robolectric.dependency.resolver.enabled', 'true'
//            }
//        }
//    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.androidx.constraintlayout
    implementation libs.kotlin.stdlib

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.work.runtime.ktx
//    implementation libs.material
    testImplementation libs.junit
    implementation libs.mockito.core
    testImplementation libs.junit.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

//    implementation libs.htmlunit
//    implementation libs.androidx.security.crypto
    implementation libs.fastjson
    implementation libs.okhttp
//    testImplementation libs.robolectric
    androidTestImplementation libs.androidx.runner
    androidTestImplementation libs.androidx.rules
    implementation libs.jsoup
    implementation libs.android.loading.animation
    implementation libs.objectbox.kotlin
    implementation libs.smartupdatedemo

    implementation 'com.umeng.umsdk:common:+'
    implementation 'com.umeng.umsdk:asms:+'
    implementation 'com.umeng.umsdk:union:+'
//    compileOnly libs.leakcanary.android
//    implementation libs.kotlin.test


}