plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.objectbox)
}

android {
    namespace 'com.feifan.fuckingnjit'
    compileSdk 35

    defaultConfig {
        minSdk 26
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation libs.kotlinx.coroutines.core
    implementation libs.androidx.core
    implementation libs.appcompat
    implementation libs.fastjson
    implementation libs.okhttp
    implementation libs.jsoup
    implementation libs.android.loading.animation
    implementation libs.smartupdatedemo
    implementation libs.androidx.lifecycle.service


    // 设备兼容框架：https://github.com/getActivity/DeviceCompat
    implementation libs.devicecompat
    // 权限请求框架：https://github.com/getActivity/XXPermissions
    implementation libs.xxpermissions
    implementation libs.fyiban

    implementation "androidx.startup:startup-runtime:1.2.0"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.10.0"
}